---
title: "Efecto de sustratos y tipo de agua de riego en el crecimiento de plántulas de frijol (Phaseolus vulgaris)"
format: html
editor_options: 
  chunk_output_type: console
---

# ANOVA
$$Y_{ij} = \mu + \tau_i +\beta_j + \varepsilon_{ij}$$
# Cargar paquetes
```{r}
library(tidyverse)
library(googlesheets4)
library(emmeans)
library(multcomp)
library(multcompView)
library(knitr)
gs4_deauth()
```

# Importar datos

```{r}
url <- "https://docs.google.com/spreadsheets/d/1bO1pannWdC3Yi7X4ZIp9fpWMoSu-9BOFucpZUbmc_tc/edit?usp=sharing"
gs <- url %>% as_sheets_id()

fb <- gs %>% range_read("fb") %>% 
  mutate(across(1: bloque, ~ as.factor(.)))

str(fb)
```

# ANOVA
$$Y_{ij} = \mu + \tau_i +\beta_j + \varepsilon_{ij}$$
## Analisis para long_plan

# ANOVA
```{r}
md_long_trt <- aov(long_plan ~ bloque + trt, data = fb)

anova(md_long_trt)

```

# Comparación de medias
```{r}
emm_long_trt <- emmeans(md_long_trt, ~ trt)

cld_long_trt <- cld(
emm_long_trt,
adjust  = "tukey",
Letters = letters,
alpha   = 0.05
) %>%
as_tibble() %>%
mutate(
.group = stringr::str_trim(.group),
y_lab  = upper.CL + 0.05 * max(upper.CL, na.rm = TRUE)
)

cld_long_trt %>% kable(digits = 3)


```

## grafico

```{r}
ggplot(cld_long, aes(x = sustrato, y = emmean, fill = riego)) +
geom_col(position = position_dodge(width = 0.8)) +
geom_errorbar(
aes(ymin = lower.CL, ymax = upper.CL),
position = position_dodge(width = 0.8),
width = 0.2
) +
geom_text(
aes(label = .group, y = y_lab),
position = position_dodge(width = 0.8),
vjust = -0.3,
size = 4
) +
labs(
x = "Sustrato",
y = "Longitud de planta (media marginal ± IC95%)",
fill = "Riego",
title = "Prueba de Tukey para longitud de planta (sustrato × riego)"
) +
theme_minimal(base_size = 13) +
theme(
plot.title      = element_text(face = "bold", hjust = 0.5),
legend.position = "top",
axis.text.x     = element_text(angle = 45, hjust = 1)
)

```



